name: Update domains.json

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Download new file
      uses: wei/curl@v1
      with:
        args: https://cdn.jsdelivr.net/gh/andreis/disposable-email-domains@master/domains.json --output domains.json

    - name: Push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        file_pattern: domains.json
        commit_message: "[AUTO] Update domains.json"
  
    - name: Bump version
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: 'patch'
